import { Symbol, SymbolType } from "../project/Project";
import { CompletionItemKind, ParameterInformation } from "vscode-languageserver";
import { Parameter } from "./KickPreprocessors";

export class KickInternalSymbols {

    constructor() {

    }

    public static getBuiltInSymbols():Symbol[]|undefined {

        return [
            /*
                COLORS
            */
            {
                type: SymbolType.Constant,
                name: "BLACK",
                comments: "The Color BLACK",
                value: 0,
                originalValue: "#$00",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "WHITE",
                comments: "The Color WHITE",
                value: 1,
                originalValue: "#$01",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "RED",
                description: "The Color RED",
                value: 2,
                originalValue: "$02",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "CYAN",
                description: "The Color CYAN",
                value: 3,
                originalValue: "$03",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "PURPLE",
                description: "The Color PURPLE",
                value: 4,
                originalValue: "$04",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "GREEN",
                description: "The Color GREEN",
                value: 5,
                originalValue: "$05",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "BLUE",
                description: "The Color BLUE",
                value: 6,
                originalValue: "$07",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "YELLOW",
                description: "The Color YELLOW",
                value: 7,
                originalValue: "$07",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "ORANGE",
                description: "The Color ORANGE",
                value: 8,
                originalValue: "$08",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "BROWN",
                description: "The Color BROWN",
                value: 9,
                originalValue: "$09",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "LIGHT_RED",
                description: "The Color LIGHT RED",
                value: 10,
                originalValue: "$10",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "DARK_GRAY",
                description: "The Color DARK_GRAY",
                value: 11,
                originalValue: "$11",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "DARK_GREY",
                description: "The Color DARK_GREY",
                value: 11,
                originalValue: "$11",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "GRAY",
                description: "The Color GRAY",
                value: 12,
                originalValue: "$12",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "GREY",
                description: "The Color GREY",
                value: 12,
                originalValue: "$12",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "LIGHT_GREEN",
                description: "The Color LIGHT_GREEN",
                value: 13,
                originalValue: "$13",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "LIGHT_BLUE",
                description: "The Color LIGHT_BLUE",
                value: 14,
                originalValue: "$14",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "LIGHT_GRAY",
                description: "The Color LIGHT_GRAY",
                value: 15,
                originalValue: "$15",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },
            {
                type: SymbolType.Constant,
                name: "LIGHT_GREY",
                description: "The Color LIGHT_GREY",
                value: 15,
                originalValue: "$15",
                kind: CompletionItemKind.Color,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
            },

            /*
                MACROS
            */
           {
                type: SymbolType.Macro,
                name: "BasicUpstart",
                description: "Creates a BASIC Program at the Address Specified.",
                value: 1,
                originalValue: "",
                kind: CompletionItemKind.Function,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
                parameters: [
                    <Parameter> {
                        name: "address",
                        type: "string",
                        description: "The Label that locates the Start of the Program."
                    }
                ]
            },
            {
                type: SymbolType.Macro,
                name: "BasicUpstart2",
                description: "Creates a BASIC Program at the Address Specified.",
                value: 1,
                originalValue: "",
                kind: CompletionItemKind.Function,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
                parameters: [
                    <Parameter> {
                        name: "address",
                        type: "string",
                        description: "The Label that locates the Start of the Program."
                    }
                ]
            },
            /*
                MATH LIB
            */
           {
                type: SymbolType.Function,
                name: "abs",
                description: "Returns the Absolute (positive) value of X. For example, the Absolute value of -2 is 2.",
                value: 1,
                originalValue: "",
                kind: CompletionItemKind.Function,
                scope: 0,
                isExternal: false,
                isGlobal: true,
                isMain: false,
                isBuiltin: true,
                parameters: [
                    <Parameter> {
                        name: "x",
                        type: "value",
                        description: "Numeric Expression for which the Absolute Value is needed."
                    }
                ]
            },
    ];
    }
}